[package]
name = "regex-engine"
version = "0.1.0"
edition = "2021"

[features]
debug = []


# CLI
[[bin]]
name = "regex-engine"
path = "src/main.rs"


# Demo
[[example]]
name = "demo_match"
path = "examples/demo_match.rs"

[[example]]
name = "demo_posix"
path = "examples/demo_posix.rs"

[[example]]
name = "demo_crash"
path = "examples/demo_crash.rs"


# Benchmarks
[[bench]]
name = "bench_match"
harness = false

[[bench]]
name = "bench_posix"
harness = false


# Tests

# Dependencies
[dependencies]
clap   = { version = "4.5", features = ["derive"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

